sudo: required
language: generic
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - docker build -t mirks/gh-profiles -f ./Dockerfile.dev .

script:
  - docker run -e CI=true mirks/gh-profiles yarn test

# push to docker hub, login to docker cli w/ travis, push built images to docker hub
after_success:
  - docker build -t mirks/gh-profiles:latest -t mirks/gh-profiles:$SHA .
  #  docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mirks/gh-profiles:latest
  - docker push mirks/gh-profiles:$SHA
  - docker run mirks/gh-profiles:latest